# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "212ddbfebce4e63311e32a2efec908a8"
name = "age-validation-extension"
handle = "age-validation-extension"
application_url = "https://attached-album-blacks-issued.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "functions-fernando.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://attached-album-blacks-issued.trycloudflare.com/auth/callback",
  "https://attached-album-blacks-issued.trycloudflare.com/auth/shopify/callback",
  "https://attached-album-blacks-issued.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
