# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79eb1174b6937003ebb622e40b7d34d5"
name = "age verification"
handle = "age-verification-52"
application_url = "https://enabled-brings-keys-teen.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "functions-fernando.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://enabled-brings-keys-teen.trycloudflare.com/auth/callback",
  "https://enabled-brings-keys-teen.trycloudflare.com/auth/shopify/callback",
  "https://enabled-brings-keys-teen.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
